// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package core

import (
	"context"
)

import (
	_ "github.com/go-sql-driver/mysql"
)

// Injectors from wire.go:

func InitializeApp(ctx context.Context, confPath ConfigPath) (*App, error) {
	validator, err := provideValidator()
	if err != nil {
		return nil, err
	}
	appConfig, err := provideAppConfig(confPath, validator)
	if err != nil {
		return nil, err
	}
	logger := provideLogger()
	clock := provideClock()
	mySQLContainer, err := provideMySQLContainer(appConfig)
	if err != nil {
		return nil, err
	}
	taskService := provideTaskService(clock, mySQLContainer)
	server := provideServer(appConfig, logger, taskService)
	app := provideApp(appConfig, server)
	return app, nil
}
