// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package core

import (
	"context"
)

import (
	_ "github.com/go-sql-driver/mysql"
)

// Injectors from wire.go:

func InitializeApp(ctx context.Context, confPath ConfigPath) (*App, error) {
	appConfig, err := provideAppConfig(confPath)
	if err != nil {
		return nil, err
	}
	serverConfig := appConfig.Server
	mySQLConfig := appConfig.MySQL
	mySQL, err := provideMySQL(mySQLConfig)
	if err != nil {
		return nil, err
	}
	taskService := provideTaskService(mySQL)
	server := provideServer(serverConfig, taskService)
	app := provideApp(server)
	return app, nil
}
