import type { CodegenConfig } from '@graphql-codegen/cli';

const config: CodegenConfig = {
  overwrite: true,
  schema: './schema/gql/*.gql',
  documents: './gql/**/*.gql',
  generates: {
    './src/gen/graphql-codegen/schema.ts': {
      plugins: [
        {
          add: {
            content: '// Code generated by graphql-codegen. DO NOT EDIT.',
          },
        },
        {
          add: {
            content:
              'export type Int64String = string & { __int64StringBrand: any };',
          },
        },
        {
          add: {
            content:
              'export type Uint64String = string & { __uint64StringBrand: any };',
          },
        },
        'typescript',
        'typescript-operations',
        'typescript-apollo-angular',
      ],
      config: {
        scalars: {
          Int32: 'number',
          Int64: 'Int64String',
          Uint32: 'number',
          Uint64: 'Uint64String',
        },
      },
    },
  },
};

export default config;
