name: web-app-example
services:
  frontend:
    build: ./frontend
    ports:
      - 4200:4200
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - 8080:8080
    environment:
      APP_MYSQL_APP_HOST: mysql
      APP_MYSQL_APP_PASSWORD: my-secret-pw
      APP_SERVER_WITH_PLAYGROUND: true
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    configs:
      - source: mysql_app_schema
        target: /docker-entrypoint-initdb.d/schema.sql
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: app
      TZ: UTC
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysql -h localhost -u root -p$$MYSQL_ROOT_PASSWORD -e 'SELECT 1;'"
        ]
      interval: 1s
      start_period: 30s
      retries: 30
configs:
  mysql_app_schema:
    file: ./schema/sql/app.sql
