name: web-app-sample
services:
  backend:
    build: ./backend
    ports:
      - 8080:8080
    environment:
      APP_DB_MYSQL_HOST: mysql
      APP_DB_MYSQL_PASSWORD: my-secret-pw
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: mysql:8.0
    configs:
      - source: mysql_schema
        target: /docker-entrypoint-initdb.d/schema.sql
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: app
      TZ: UTC
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysql -h localhost -u root -p$$MYSQL_ROOT_PASSWORD -e 'SELECT 1;'"
        ]
      interval: 1s
      start_period: 30s
      retries: 30
configs:
  mysql_schema:
    file: ./schema/sql/schema.sql
