// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"app/db"
	"app/env"
	"app/service"
	"app/service/app/v1"
	"context"
)

// Injectors from wire.go:

func InitializeApp(ctx context.Context, conf Config) (*App, error) {
	serverConfig := conf.Server
	config := conf.DB
	container, err := db.NewContainer(config)
	if err != nil {
		return nil, err
	}
	envContainer := env.NewContainer(container)
	base := service.NewBase(envContainer)
	taskService := appv1.NewTaskService(base)
	server := NewServer(serverConfig, taskService)
	app := NewApp(server)
	return app, nil
}
