db:
  mysql:
    host: "<% env `APP_DB_MYSQL_HOST` `127.0.0.1` %>"
    port: <% env `APP_DB_MYSQL_PORT` `3306` %>
    user: "<% env `APP_DB_MYSQL_USER` `root` %>"
    password: "<% must_env `APP_DB_MYSQL_PASSWORD` %>"
    db_name: "<% env `APP_DB_MYSQL_DB_NAME` `app` %>"
server:
  port: <% env `APP_SERVER_PORT` `8080` %>
