mysql:
  host: "<% env `APP_MYSQL_HOST` `127.0.0.1` %>"
  port: <% env `APP_MYSQL_PORT` `3306` %>
  user: "<% env `APP_MYSQL_USER` `root` %>"
  password: "<% must_env `APP_MYSQL_PASSWORD` %>"
  db_name: "<% env `APP_MYSQL_DB_NAME` `app` %>"
runtime:
  env: "<% must_env `APP_RUNTIME_ENV` %>"
sentry:
  dsn: "<% env `APP_SENTRY_DSN` `` %>"
server:
  port: <% env `APP_SERVER_PORT` `8080` %>
