mysql:
  app:
    host: <% env `APP_MYSQL_APP_HOST` `127.0.0.1` %>
    port: <% env `APP_MYSQL_APP_PORT` `3306` %>
    user: <% env `APP_MYSQL_APP_USER` `root` %>
    password: <% must_env `APP_MYSQL_APP_PASSWORD` %>
    name: <% env `APP_MYSQL_APP_NAME` `app` %>
server:
  port: <% env `APP_SERVER_PORT` `8080` %>
  with_playground: <% env `APP_SERVER_WITH_PLAYGROUND` `false` %>
