scalar Int32

scalar Int64

scalar Uint32

scalar Uint64

interface Node {
  id: ID!
}

interface IConnection {
  pageInfo: PageInfo!
  totalCount: Int64!
}

type PageInfo {
  endCursor: String
  hasNextPage: Boolean!
}

input NoopInput {
  clientMutationId: String
}

type NoopPayload {
  clientMutationId: String
}

interface Error {
  message: String!
}

type BadRequestError implements Error {
  message: String!
}

type Query {
  node(id: ID!): Node
}

type Mutation {
  noop(input: NoopInput!): NoopPayload!
}
