mutation HomePage_CreateTask($input: CreateTaskInput!) {
  createTask(input: $input) {
    error {
      ... on BadRequestError {
        message
      }
    }
  }
}

mutation HomePage_CompleteTask($input: CompleteTaskInput!) {
  completeTask(input: $input) {
    error {
      ... on BadRequestError {
        message
      }
    }
  }
}
