query HomePage_ListTasks($status: TaskStatus!, $after: String, $first: Int32!) {
  tasks(status: $status, after: $after, first: $first) {
    edges {
      node {
        id
        title
        status
      }
    }
    pageInfo {
      endCursor
      hasNextPage
    }
  }
}
