query HomePage_ListTasks($status: TaskStatus!, $first: Int32!, $after: String) {
  tasks(status: $status, first: $first, after: $after) {
    edges {
      node {
        id
        title
        status
      }
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
