mutation CreateTask($input: CreateTaskInput!) {
  createTask(input: $input) {
    task {
      id
      title
      status
    }
    error {
      ... on BadRequestError {
        message
      }
    }
  }
}

mutation CompleteTask($input: CompleteTaskInput!) {
  completeTask(input: $input) {
    task {
      id
      title
      status
    }
    error {
      ... on BadRequestError {
        message
      }
    }
  }
}
