CREATE TABLE task (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  status ENUM('TASK_STATUS_UNCOMPLETED', 'TASK_STATUS_COMPLETED') NOT NULL DEFAULT 'TASK_STATUS_UNCOMPLETED',
  updated_at BIGINT UNSIGNED NOT NULL DEFAULT (UNIX_TIMESTAMP(NOW())),
  created_at BIGINT UNSIGNED NOT NULL DEFAULT (UNIX_TIMESTAMP(NOW())),
  PRIMARY KEY (`id`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;
