CREATE TABLE task (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  display_id VARCHAR(16) DEFAULT NULL,
  title VARCHAR(255) NOT NULL,
  status TINYINT UNSIGNED DEFAULT 1 NOT NULL CHECK (status IN (1, 2)),
  updated_at BIGINT UNSIGNED NOT NULL DEFAULT (UNIX_TIMESTAMP(NOW())),
  created_at BIGINT UNSIGNED NOT NULL DEFAULT (UNIX_TIMESTAMP(NOW())),
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_display_id` (`display_id`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;
