CREATE TABLE task (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  status TINYINT UNSIGNED NOT NULL DEFAULT 1,
  updated_at BIGINT UNSIGNED NOT NULL DEFAULT (UNIX_TIMESTAMP(NOW())),
  created_at BIGINT UNSIGNED NOT NULL DEFAULT (UNIX_TIMESTAMP(NOW())),
  PRIMARY KEY (`id`),
  KEY `idx_status` (`status`),
  CONSTRAINT `chk_status` CHECK (`status` IN (1, 2))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_bin;
