mutation CreateTask($input: CreateTaskInput!) {
  createTask(input: $input) {
    task {
      id
      title
      status
    }
  }
}

mutation CompleteTask($input: CompleteTaskInput!) {
  completeTask(input: $input) {
    task {
      id
      title
      status
    }
  }
}
