name: backend-test
on:
  push:
    branches:
      - "**"
    paths:
      - .github/workflows/backend-test.yaml
      - backend/**
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: backend/go.mod
          cache-dependency-path: backend/go.sum
      - name: Test
        run: make test
