name: schema-proto-lint
on:
  push:
    branches:
      - "**"
    paths:
      - .github/workflows/schema-proto-lint.yaml
      - schema/proto/**
jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: schema
    steps:
      - name: Set up buf
        uses: bufbuild/buf-setup-action@v1
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lint
        uses: bufbuild/buf-lint-action@v1
        with:
          input: schema/proto
