name: test
on:
  push:
    branches:
      - "**"
    paths:
      - backend/**
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: backend/go.mod
      - name: Test
        run: make test
